---
- name: Check if kubectl is installed
  command: which kubectl
  register: kubectl_exists
  ignore_errors: true
  changed_when: false

- name: Install kubectl
  block:
    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'
      register: kubectl_download

    - name: Install kubectl binary
      become: true
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes

    - name: Clean up temporary kubectl binary
      file:
        path: /tmp/kubectl
        state: absent
  when: kubectl_exists.rc != 0
  vars:
    kubectl_version:
      stdout: "{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}"
