---
- name: Install and configure Jenkins, Docker, and other tools
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install core packages
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Add Jenkins repository key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins.list

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes
        state: present

    - name: Ensure Jenkins is running and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Restart Jenkins service
      service:
        name: jenkins
        state: restarted

    - name: Install Trivy dependencies
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
          - snapd
        state: present

    - name: Add Trivy repository key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
        state: present
        filename: trivy.list

    - name: Install Trivy
      apt:
        name: trivy
        update_cache: yes
        state: present

    - name: Install AWS CLI via snap
      snap:
        name: aws-cli
        classic: yes
        state: present

    - name: Install Helm via snap
      snap:
        name: helm
        classic: yes
        state: present

    - name: Install kubectl via snap
      snap:
        name: kubectl
        classic: yes
        state: present