apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z mongodb-service 27017; do echo "Waiting for MongoDB to be ready..."; sleep 2; done;']
      containers:
      - name: migration
        image: iemafzal/easyshop-migration:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
