---
- name: Uninstall old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_os_family == "Debian"

- name: Install prerequisites and set up Docker repository
  block:
    - name: Install prerequisites
      apt:
        name: "{{ docker_prerequisites }}"
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Remove conflicting Docker repository entries
      ansible.builtin.command:
        cmd: "rm -f /etc/apt/sources.list.d/docker.list"
      become: yes
      ignore_errors: yes

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: yes

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes
  when: ansible_os_family == "Debian"

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Set up Docker service and user permissions
  block:
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
  when: docker_users_to_group is defined
