---
- name: Uninstall old versions of Docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_os_family == "Debian"

- name: Install prerequisites and set up Docker repository
  block:
    - name: Install prerequisites
      apt:
        name: "{{ docker_prerequisites }}"
